Description: >
  This template deploys an Application Load Balancer that exposes our various ECS services.
  We create them it a seperate nested template, so it can be referenced by all of the other nested templates.

Parameters:
  EnvironmentName:
    Type: String
    Description: Name for listeners
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Applicaion Load Balancer should be deployed to
  Subnets:
    Description: Choose which subnets the Applicaion Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroups:
    Description: Select the Security Group to apply to the Applicaion Load Balancer
    Type: List<AWS::EC2::SecurityGroup::Id>
  Scheme:
    Description: Internal or internet facing
    Type: String
    AllowedValues:
    - internal
    - internet-facing

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}
      Subnets: !Ref Subnets
      SecurityGroups: !Ref SecurityGroups
      Scheme: !Ref Scheme
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}

  LoadBalancerListenerHttp:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref DefaultTargetGroupHttp

  DefaultTargetGroupHttp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub http-${EnvironmentName}
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: 20

Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer
    Export:
      Name: !Sub load-balancer-${EnvironmentName}

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName

  ListenerHttp:
    Description: A reference to a port 80 listener
    Value: !Ref LoadBalancerListenerHttp

  HostedZoneId:
    Description: A reference to the load balancer's hosted zone
    Value: !GetAtt LoadBalancer.CanonicalHostedZoneID
